language: node_js

node_js:
  - "6.7.0"
  - "4.6.0"
  - "0.12.16"
  - "iojs"

install:
    - npm install
    - npm install -g codecov
    - npm install istanbul
  
script: 
    - npm test test/test.js
    - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)